
name: Build and deploy ASP.Net Core app to Azure Web App - BadgerClanApi1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: dotnet build BadgerClan.Api --configuration Release

      - name: dotnet publish
        run: dotnet publish BadgerClan.Api -c Release -o ${{env.DOTNET_ROOT}}/myapi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-api
          path: ${{env.DOTNET_ROOT}}/myapi

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-api
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9324FBCEA4CC4A4E8643BD86D5A7C9F4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C3546E8F416443A1B9A3900EC3059AF1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4049BBD6EFDE4BFBA5DC001F4A146357 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BadgerClanApi1'
          slot-name: 'Production'
          package: .
          